---
- name: Install tomcat
  hosts: localhost
  tasks:
    - name: install tomcat
      apt:
        name: apache2
        state: present
    - name: edit index.html
      copy:
        content: "Welcome to playbooks/n"
        dest: /var/www/html/index.html
